version: '3.8'

services:
  # ==================== Infrastructure ====================

  # Redis for event streaming
  redis:
    image: docker.io/redis:7-alpine
    container_name: oteldemo-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - oteldemo

  # Jaeger all-in-one for trace visualization
  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.51
    container_name: oteldemo-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
    networks:
      - oteldemo

  # ==================== Central OTEL Collector ====================

  central-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.91.0
    container_name: oteldemo-central-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collectors/central-config.yaml:/etc/otel-collector-config.yaml:ro
    environment:
      - COLLECTOR_API_KEY=${COLLECTOR_API_KEY}
      - JAEGER_ENDPOINT=jaeger:4317
    ports:
      - "4319:4317"    # OTLP gRPC (external access)
      - "13133:13133"  # Health check
      - "55679:55679"  # zpages
      - "8888:8888"    # Metrics
    depends_on:
      - jaeger
    networks:
      - oteldemo

  # ==================== Sidecar OTEL Collectors ====================

  gateway-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.91.0
    container_name: oteldemo-gateway-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collectors/sidecar-config.yaml:/etc/otel-collector-config.yaml:ro
    environment:
      - COLLECTOR_NAME=gateway-collector
      - COLLECTOR_API_KEY=${COLLECTOR_API_KEY}
      - CENTRAL_COLLECTOR_ENDPOINT=central-collector:4317
    depends_on:
      - central-collector
    networks:
      - oteldemo

  orchestrator-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.91.0
    container_name: oteldemo-orchestrator-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collectors/sidecar-config.yaml:/etc/otel-collector-config.yaml:ro
    environment:
      - COLLECTOR_NAME=orchestrator-collector
      - COLLECTOR_API_KEY=${COLLECTOR_API_KEY}
      - CENTRAL_COLLECTOR_ENDPOINT=central-collector:4317
    depends_on:
      - central-collector
    networks:
      - oteldemo

  worker-us-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.91.0
    container_name: oteldemo-worker-us-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collectors/sidecar-config.yaml:/etc/otel-collector-config.yaml:ro
    environment:
      - COLLECTOR_NAME=worker-us-collector
      - COLLECTOR_API_KEY=${COLLECTOR_API_KEY}
      - CENTRAL_COLLECTOR_ENDPOINT=central-collector:4317
    depends_on:
      - central-collector
    networks:
      - oteldemo

  worker-eu-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.91.0
    container_name: oteldemo-worker-eu-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collectors/sidecar-config.yaml:/etc/otel-collector-config.yaml:ro
    environment:
      - COLLECTOR_NAME=worker-eu-collector
      - COLLECTOR_API_KEY=${COLLECTOR_API_KEY}
      - CENTRAL_COLLECTOR_ENDPOINT=central-collector:4317
    depends_on:
      - central-collector
    networks:
      - oteldemo

  worker-asia-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.91.0
    container_name: oteldemo-worker-asia-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collectors/sidecar-config.yaml:/etc/otel-collector-config.yaml:ro
    environment:
      - COLLECTOR_NAME=worker-asia-collector
      - COLLECTOR_API_KEY=${COLLECTOR_API_KEY}
      - CENTRAL_COLLECTOR_ENDPOINT=central-collector:4317
    depends_on:
      - central-collector
    networks:
      - oteldemo

  # ==================== Application Services ====================

  # Java Gateway Service
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Containerfile
    container_name: oteldemo-gateway
    environment:
      - ORCHESTRATOR_URL=http://orchestrator:8001
      - OTEL_SERVICE_NAME=dns-gateway
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://gateway-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    ports:
      - "8080:8080"
    depends_on:
      - orchestrator
      - gateway-collector
    networks:
      - oteldemo

  # Python Orchestrator Service
  orchestrator:
    build:
      context: ./services/orchestrator
      dockerfile: Containerfile
    container_name: oteldemo-orchestrator
    environment:
      - REDIS_URL=redis://redis:6379
      - OTEL_SERVICE_NAME=dns-orchestrator
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://orchestrator-collector:4317
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - orchestrator-collector
    networks:
      - oteldemo

  # Go Worker Services (simulating different geo locations)

  worker-us-east:
    build:
      context: ./services/workers
      dockerfile: Containerfile
    container_name: oteldemo-worker-us-east
    environment:
      - WORKER_LOCATION=us-east-1
      - REDIS_URL=redis://redis:6379
      - OTEL_SERVICE_NAME=dns-worker-us-east-1
      - OTEL_EXPORTER_OTLP_ENDPOINT=central-collector:4317
      - HTTP_PORT=8080
    ports:
      - "8082:8080"
    depends_on:
      - redis
      - central-collector
    networks:
      - oteldemo

  worker-eu-west:
    build:
      context: ./services/workers
      dockerfile: Containerfile
    container_name: oteldemo-worker-eu-west
    environment:
      - WORKER_LOCATION=eu-west-1
      - REDIS_URL=redis://redis:6379
      - OTEL_SERVICE_NAME=dns-worker-eu-west-1
      - OTEL_EXPORTER_OTLP_ENDPOINT=central-collector:4317
      - HTTP_PORT=8080
    ports:
      - "8083:8080"
    depends_on:
      - redis
      - central-collector
    networks:
      - oteldemo

  worker-asia-south:
    build:
      context: ./services/workers
      dockerfile: Containerfile
    container_name: oteldemo-worker-asia-south
    environment:
      - WORKER_LOCATION=asia-south-1
      - REDIS_URL=redis://redis:6379
      - OTEL_SERVICE_NAME=dns-worker-asia-south-1
      - OTEL_EXPORTER_OTLP_ENDPOINT=central-collector:4317
      - HTTP_PORT=8080
    ports:
      - "8084:8080"
    depends_on:
      - redis
      - central-collector
    networks:
      - oteldemo

networks:
  oteldemo:
    driver: bridge
